"""Code generation agent for producing production-ready source files."""
import json
import logging
from typing import Any, Dict, List, Optional

from core.kernel import NexusKernel
from core.memory_bank import memory_bank
from tools.shell import PythonExecutor

logger = logging.getLogger(__name__)


class CoderAgent:
    """Generate cross-file-consistent source code for requested deliverables."""

    def __init__(self, kernel: NexusKernel):
        self.kernel = kernel
        self.py_exec = PythonExecutor()

    async def build_files(
        self,
        task: str,
        files_to_create: List[str],
        provider: str,
        model: str,
        api_key: Optional[str] = None,
        max_retries: int = 3,
    ) -> Dict[str, str]:
        """Ask the model for a file map and retry parsing failures up to *max_retries* times."""
        logger.info("CoderAgent.build_files task=%s file_count=%d", task, len(files_to_create))
        prompt = f"""You are the Nexus Full-Stack Coder. Your goal is to generate high-quality, production-ready code for the following task and files.

Task: {task}
Files to Create: {files_to_create}

Task:
1. Write the complete source code for each requested file.
2. Ensure cross-file consistency (e.g., API endpoints in 'backend/' must match 'frontend/' calls).
3. Follow 2026 best practices: TypeScript, FastAPI, React Hooks, Tailwind CSS.
4. Output your code as a JSON object with keys: 'files' (key-value mapping of paths to file content).

Output ONLY the JSON object."""
        messages = [{"role": "user", "content": prompt}]

        for attempt in range(1, max_retries + 1):
            try:
                logger.info("CoderAgent attempt=%d/%d", attempt, max_retries)
                res_content = await self.kernel.chat_async(provider, model, messages, api_key=api_key)
                payload = self.kernel.extract_json(res_content)
                files = payload.get("files", {})
                memory_bank.store_success(task=task, code=json.dumps(files), brief="Generated by CoderAgent")
                logger.info("CoderAgent generated %d files", len(files))
                return files
            except Exception as exc:
                logger.error("CoderAgent attempt=%d failed: %s", attempt, exc, exc_info=True)

        return {}
